name: 'ElementalMenus'

version: '${project.version}'

main: 'me.lokka30.elementalmenus.ElementalMenus'

description: '${project.description}'

api-version: '1.13'

load: 'POSTWORLD'

softdepend: ['Vault']

commands:
  elementalmenus:
    description: 'Manage the ElementalMenus plugin.'
    aliases: [ 'menu', 'menus', 'elementalmenu', 'emenu', 'emenus' ]

permissions:
  elementalmenus.*:
    default: op
    description: 'All permissions for the ElementalMenus plugin.'
#TODO